<?xml version="1.0" encoding="utf-8"?><Database Name="dwh" Class="IADataClassessDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=192.168.1.39;Initial Catalog=dwh;Integrated Security=True" SettingsObjectName="SyncData.Properties.Settings" SettingsPropertyName="dwhConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BILLS" Member="BILLs">
    <Type Name="BILL">
      <Column Name="DOC_ID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SMEN_ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="PAYMENT" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SALETYPE" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DISCOUNT" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="DCARD" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="BCARD" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="BCARD_TYPE" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="BONUS_BEFORE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BONUS_ADD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BONUS_LIMIT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BONUS_PAY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BONUS_ENABLE" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>